version: "3.5"
services:
  nginx-seed:
    image: nginx
    container_name: nginx-seed
    restart: always
    ports:
      - 3999:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html/
volumes:
  html: {}
