# prettier-ignore
version: "3.5"
services:
  server:
    build: .
    restart: always    
    networks:
      - uw2
    ports:
      - ${APPLICATION_SERVER_PORT}:8080    
volumes:
  html: {}

networks:
  uw2:
    external: true
